vscode:
    extensions:
      - ms-dotnettools.csharp@1.21.17:5/iI88WHX4j3iL5jASDTYQ==
      - formulahendry.dotnet-test-explorer@0.7.1:aMBBHLwB96Y4mOqZ8ucTKw==
      - formulahendry.code-runner@0.10.0:PU5QMJYXy+CAccMJUocvnA==
